# Generated by Django 4.2.3 on 2023-07-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField()),
                ('created_by', models.CharField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField()),
                ('updated_date', models.DateField(auto_now=True)),
                ('deleted_by', models.CharField()),
                ('deleted_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField()),
                ('website', models.URLField()),
                ('contacts', models.TextField()),
                ('audit_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.audit_field')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100, unique=True)),
                ('audit_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.audit_field')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('audit_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.audit_field')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_URL', models.URLField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('job_notes', models.TextField()),
                ('audit_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.audit_field')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.company')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.folder')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('date_applied', models.DateField()),
                ('deadline', models.DateField()),
                ('related_information', models.TextField()),
                ('audit_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.audit_field')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.job')),
            ],
        ),
    ]
