# Generated by Django 4.2.3 on 2023-08-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_audit_field_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_URL',
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(null=True),
        ),
    ]
