# Generated by Django 4.2.3 on 2023-08-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_company_contacts_remove_job_job_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='related_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
