name: Docker Image CI

on:
  push:
    branches: [ "dockerize" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      # run: docker build -t job-application-tracker .
      run: docker build . --file ./ui/Dockerfile --tag job-application-tracker:$(date +%s)
    - name: Push to Dockerhub
      run: docker push rxmei/job-application-tracker:latest
